name: Npm Relase

inputs:
  node-version:
    required: false
    default: "22.11.0"
    type: string
    description: node version
  app-path:
    required: true
    type: string
    description: path where the package.json is located
  releaseVersion:
        type: choice
        description: "Select version increment type (follows Semantic Versioning)"
        required: true
        options:
          - patch
          - minor
          - major    
  skipDeployment:
     default: true
     type: boolean
     description: skip deployment to npm registry
outputs:
  ARTIFACT_NAME:
    description: "artifact name from pom"
    value: ${{ steps.node.outputs.artifact-name }}
  VERSION: 
     description: "name of the artifact upload"
     value: ${{steps.node-release.outputs.VERSION}}   

runs:
    using: "composite"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.node-version }}"
          registry-url: 'https://registry.npmjs.org'
      - id: node-release
        name: Bump version and create git tag
        working-directory: ./${{inputs.app-path}}
        run: |
         NEW_VERSION=$(npm version ${{inputs.releaseVersion}}) || exit 1
         echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
         git add package.json package-lock.json
         git commit -m "Bump version to ${NEW_VERSION}" || exit 1
         git tag "${NEW_VERSION}" || exit 1
         git push && git push --tags || exit 1
      - id: node
        uses: it-at-m/.github/.github/actions/action-npm-build@main
        with:
          app-path:  "${{ inputs.app-path }}"
      - if: "${{ !inputs.skipDeployment }}"
        run: npm --prefix ./${{ inputs.app-path }} publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Centralized token in it-at-m GitHub organization
