name: Npm Release

inputs:
  node-version:
    required: false
    default: "22.11.0"
    type: string
    description: node version
  app-path:
    required: true
    type: string
    description: path where the package.json is located
  releaseVersion:
        type: choice
        description: "Select version increment type (follows Semantic Versioning)"
        required: true
        options:
          - patch
          - minor
          - major    
  skip-deployment:
     default: true
     type: boolean
     description: skip deployment to npm registry
  npm-token: 
   type: string
   required: true
   description: npm token for release
     
outputs:
  ARTIFACT_NAME:
    description: "artifact name from job artifact"
    value:  ${{ steps.node.outputs.artifact-name }}
  ARTIFACT_VERSION: 
     description: "version of the artifact upload"
     value: ${{steps.node-release.outputs.VERSION}}  

runs:
    using: "composite"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "${{ inputs.node-version }}"
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"
          cache-dependency-path: "./${{inputs.app-path}}/package-lock.json"
      - id: node-release
        name: Bump version and create git tag
        working-directory: ./${{inputs.app-path}}
        run: |
         NEW_VERSION=$(npm version ${{inputs.releaseVersion}}) || exit 1
         echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
         git add package.json package-lock.json
         git commit -m "Bump version to ${NEW_VERSION}" || exit 1
         git tag "${NEW_VERSION}" || exit 1
         git push && git push --tags || exit 1
        shell: bash
      - id: node
        uses: it-at-m/.github/.github/actions/action-npm-build@main
        with:
          app-path:  "${{ inputs.app-path }}"
      - if: "${{ !inputs.skip-deployment }}"
        shell: bash
        working-directory: ./${{inputs.app-path}}
        run: npm --prefix ./${{ inputs.app-path }} publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ inputs.npm-token }} # Centralized token in it-at-m GitHub organization
