name: Create GitHub Release
description: "Creates a GitHub Release of a Maven Artifact"
inputs:
  artifact-name:
    required: true
    type: string
    description: "name of the artifact to download"
  tag-name:
    required: true
    type: string
    description: "Name of a tag (e.g. sps-1.0.0 or myproject-1.0.0"
  artifact-path:
    required: true
    type: string
    description: "path to the artifacts (e.g. ./target/*.jar)"
runs:
  using: "composite"
  steps:
    - name: Download a single artifact
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: ${{inputs.artifact-name}}
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        tag_name: ${{inputs.tag-name}}
        draft: false
        prerelease: false
        generate_release_notes: false
        files: |
          ${{inputs.artifact-path}}
