name: "Checkout Code"
description: "A wrapper for actions/checkout with no args"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
