name: 'Hello World'
description: 'Greet someone'

inputs:
      registry:
        required: true
        type: string
      registry-username:
        required: true
        type: string
      image-tags:
         required: false
         default: |
            type=raw,value=latest
         type: string
      image-labels:
          required: false
          default: |
           org.opencontainers.image.description=Siehe ${{ github.server_url }}/${{ github.repository }}
          type: string
      app-path:
        required: true
        type: string
     secrets:
      registry-password:
        required: true


        
runs:

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: target
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ github.repository }}${{ inputs.app-path }}
          tags: ${{inputs.image-tags}}
          labels: ${{inputs.image-labels}}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .${{ inputs.app-path }}
          push: true          
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
