# https://vitepress.dev/guide/deploy#github-pages
name: Build docs

inputs:
  docs-path:
    required: false
    default: "./docs"
    type: string
    description: Path to vitepress docs project
  node-version:
    required: false
    default: "22"
    type: string
    description: Node version
  build-cmd:
    required: false
    default: "build"
    type: string
    description: change the build command, for use of vuepress
  dist-path:
    required: false
    default: ".vitepress/dist"
    type: string
    description: output path of vite, which should be uploaded to github pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0 # Required for vitepress lastUpdated
    - name: Setup Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: "${{ inputs.sub-path }}/package-lock.json"
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - name: Install dependencies
      run: npm --prefix ./${{inputs.sub-path }}  ci
      shell: bash
    - name: Run lint
      run: npm run --prefix  ./${{inputs.sub-path}} lint
      shell: bash
    - name: Build with VitePress
      run: npm --prefix ./${{inputs.sub-path }} run ${{ inputs.build-cmd }}
      shell: bash
    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: ${{ inputs.sub-path }}/${{ inputs.dist-path }}
