name: Compliance check and build test

inputs:
  java-version:
    required: false
    default: 17
    type: string
  enable-node:
    required: false
    default: false
    type: boolean
  node-version:
    required: false
    default: 20
    type: string
  app-path:
    required: true
    type: string

runs:
  using: "composite"
 # env:
 #   TZ: Europe/Berlin # timezone
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
    - name: Set up Node.js
      if: ${{ inputs.enable-node == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs }}
        cache: "npm"
        cache-dependency-path: "${{inputs.app-path}}/**/package-lock.json"
    - name: Build with Maven
      run: mvn --update-snapshots -f ${{inputs.app-path}}/pom.xml install
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: "**/target"
        retention-days: 5
