name: Compliance check and build test
inputs:
  node-version:
    required: false
    default: "22.11.0"
    type: string
    description: node version
  app-path:
    required: true
    type: string
    description: path where the package.json is located
  run-lint:
    required: false
    default: 'true'
    description: Controls the execution of the 'npm run lint' script
  run-test:
    required: false
    default: 'true'
    description: Controls the execution of the 'npm run test' script
outputs: 
  artifact-name: 
    description: "name of the artifact upload"
    value: ${{steps.artifact-name.outputs.artifact-name}}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: "./${{inputs.app-path}}/package-lock.json"
    - name: Install dependencies
      run: npm --prefix ./${{inputs.app-path}} ci
      shell: bash
    - name: Run lint
      if: ${{ inputs.run-lint == 'true' }}
      run: npm run --prefix  ./${{inputs.app-path}} lint
      shell: bash
    - name: Run test
      if: ${{ inputs.run-test == 'true' }}
      run: npm run  --prefix ./${{inputs.app-path}} test
      shell: bash
    - name: Run build
      run: npm run  --prefix ./${{inputs.app-path}} build
      shell: bash
    - id: artifact-name
      run: echo "artifact-name=${{hashFiles(format('./{0}/package.json', inputs.app-path))}}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: "Upload Artifact"
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{steps.artifact-name.outputs.artifact-name}}
        path: "**/dist"
        retention-days: 5
