name: Compliance check and build test

inputs:
  node-version:
    required: false
    default: 20
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pwd
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Run lint
      run: npm run lint
      shell: bash
    - name: Run test
      run: npm run test:unit
      shell: bash
    - name: Run build
      run: npm run build
      shell: bash
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: target
        path: "**/dist"
        retention-days: 5
