name: release-maven-image

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      app-path:
        type: choice
        description: Service-Name
        required: true
        options:
          - sps-backend # todo: muss angepasst werden. eigenen Ordner verwenden
          - sps-frontend # todo: muss angepasst werden. eigenen Ordner verwenden

jobs:
  release-maven:
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.maven-release-step.outputs.artifact-name }}
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - id: maven-release-step
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          app-path: "/${{ github.event.inputs.app-path }}"
          releaseVersion: "${{ github.event.inputs.releaseVersion }}"
          developmentVersion: "${{ github.event.inputs.developmentVersion }}"
          java-version: 17

  build-image:
    runs-on: ubuntu-latest
    needs: release-maven
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          path: "${{ github.event.inputs.app-path }}"
          image-name: "${{ github.event.inputs.app-path }}"
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.releaseVersion }}

  create-github-release:
    needs: release-maven
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: it-at-m/lhm_actions/action-templates/actions/action-create-github-release@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          artifact-name: ${{ needs.release-maven.outputs.ARTIFACT_NAME }}
          tag-name: ${{ needs.release-maven.outputs.MVN_ARTIFACT_ID }}-${{ github.event.inputs.releaseVersion }}
          artifact-path: ${{ github.event.inputs.app-path }}/target/*.jar
