name: release-maven-image

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      app-path:
        type: choice
        description: Service-Name
        required: true
        options:
          - /sps-backend # todo: muss angepasst werden. eigenen Ordner verwenden
          - /sps-frontend # todo: muss angepasst werden. eigenen Ordner verwenden

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
    steps:
      - id: maven-release-step
        uses: it-at-m/.github/.github/actions/action-maven-release@reuseable-workflow
        with:
          app-path: "${{ env.app-path }}"
          releaseVersion: releaseVersion
          developmentVersion: developmentVersion

  build-image:
    runs-on: ubuntu-latest
    needs: build-maven
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: it-at-m/.github/.github/actions/action-build-image@reuseable-workflow
        with:
          app-path: "${{ env.app-path }}"
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.releaseVersion }}

  create-github-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{needs.release.outputs.MVN_ARTIFACT_ID}}-${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
          generate_release_notes: false
