name: Deploy documentation website

on:
  # Runs on pushes targeting the `main` branch
  push:
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml" # define the concrete paths on which a change triggers this action, e.g. docs/**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - id: build_docs
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-docs@07f8f5fe8b5cf856633214abb3174f82b2292e99 # v1.0.0
        with:
          app-path: ${{inputs.app-path}}
      - id: deploy_docs
        if: (github.ref_name == 'main')

        uses: it-at-m/lhm_actions/action-templates/actions/action-deploy-docs@07f8f5fe8b5cf856633214abb3174f82b2292e99 # v1.0.0
