name: build all

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # here you may change the path
          - app-path: # eg. refarch-eai
          - app-path: # eg. refarch-webcomponent
    steps:
      - uses: actions/checkout@v4
      - if:  ${{hashFiles(format('./{0}/package.json', matrix.app-path))!=null}}
        id: node
        uses: it-at-m/.github/.github/actions/action-npm-build@main
        with:
          app-path:  "${{ matrix.app-path }}"
      - if:  ${{hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null}}
        id: maven
        uses: it-at-m/.github/.github/actions/action-maven-build@main
        with:
          app-path: "${{ matrix.app-path }}"
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/.github/.github/actions/action-build-image@main
        with:
          path: "${{  matrix.app-path }}"
          image-name: "${{  matrix.app-path }}"
          artifact-name: ${{join(steps.*.outputs.artifact-name)}}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
