name: Build Maven and Node

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # here you may change the path
          - app-path: # eg. refarch-eai
          - app-path: # eg. refarch-webcomponent
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@a7d25dbabec2057695f865169fdc411d475d4667 # v1.0.19
      - if:  ${{hashFiles(format('./{0}/package.json', matrix.app-path))!=null}}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@a7d25dbabec2057695f865169fdc411d475d4667 # v1.0.19
        with:
          app-path:  "${{ matrix.app-path }}"
      - if:  ${{hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null}}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@a7d25dbabec2057695f865169fdc411d475d4667 # v1.0.19
        with:
          app-path: "${{ matrix.app-path }}"
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@a7d25dbabec2057695f865169fdc411d475d4667 # v1.0.19
        with:
          path: "${{  matrix.app-path }}"
          image-name: "${{  matrix.app-path }}"
          artifact-name: ${{join(steps.*.outputs.artifact-name)}}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
