name: Compliance check and build test

inputs:
  java-version:
    required: false
    default: 17
    type: string
  app-path:
    required: true
    type: string
outputs: 
  artifact-name: 
     description: "name of the artifact upload"
     value: ${{env.artifact-name}}
runs:
  env: 
   artifact-name: hashFiles(format('./{0}/pom.xml', matrix.app-path))
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./${{inputs.app-path}}/pom.xml"
    - name: Build with Maven
      run: mvn --update-snapshots -f ./${{inputs.app-path}}/pom.xml install
      shell: bash
    - id: upload-artifact
      name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.artifact-name}}
        path: "**/target"
        retention-days: 5
