name: Compliance check and build test

inputs:
  java-version:
    required: false
    default: 21
    type: string
    description: set the java version
  app-path:
    required: true
    type: string
    description: path to the pom.xml
outputs: 
  artifact-name: 
     description: "name of the artifact upload"
     value: ${{steps.artifact-name.outputs.artifact-name}}
runs:

  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./${{inputs.app-path}}/pom.xml"
    - name: Build with Maven
      run: mvn --update-snapshots -f ./${{inputs.app-path}}/pom.xml install
      shell: bash
    - id: artifact-name
      run: echo "artifact-name=${{hashFiles(format('./{0}/pom.xml', inputs.app-path))}}" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: upload-artifact
      name: "Upload Artifact"
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: ${{steps.artifact-name.outputs.artifact-name}}
        path: "**/target"
        retention-days: 5
