name: Compliance check and build test

inputs:
  java-version:
    required: false
    default: 17
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./pom.xml"
    - name: Build with Maven
      run: mvn --update-snapshots install
      shell: bash
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4
      with:
        name: target1
        path: "**/target"
        retention-days: 5
