# Sample workflow for building and deploying a VitePress site to GitHub Pages
#
name: Deploy VitePress site to Pages

on:
  workflow_call:

jobs:
  deploy-pages:
    uses: it-at-m/.github/.github/workflows/reuseable-template-deploy-pages.yml@reuseable-workflow
